from distutils.core import setup
setup(
    name='valvesmd',
    packages=['valvesmd'],
    version='0.1.0',
    license='gpl-3.0',
    description='A library to parse .smd files used in the source engine.',
    author='Maxime Dupuis',
    author_email='mdupuis@hotmail.ca',
    url='https://maxdup.github.io/pySourceSDK/ValveSMD/',
    download_url='',
    keywords=['smd', 'source', 'sourcesdk', 'hammer', 'valve'],
    install_requires=['pyparsing', 'future'],
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
)
